# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3ebb221596f4db445edc4b4ac01415c6f08b3424aa4b18b3f3282e1f7221ca3d8bc13ffaf4b8aa6f6ba3a8c05deaee9f90060b3a2a888464d8c3206a71a5ff3

test:
  secret_key_base: 1e8cf5f73a538a3c675c09797462f33fec0123b5efe7db30b6ea7f788db2aa41225276c27e5b85b09805f292df2048eb5e1f3bf6c263b56a56e8870b79ca61ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
